import Head from 'next/head';

import { Store } from '../context/store';
import { useContext, useEffect } from 'react';
import Header from '../components/Header';
import SiderBar from '../components/Sidebar';
import Banner from '../components/Banner';
import { Hotdeals } from '../components/Hotdelas';
import { SideBarDemo } from '../components/SideBarDemo';
import Cookies from 'js-cookie';

export default function Home({ products, categories }) {
  const { state, dispatch } = useContext(Store);

  useEffect(() => {
    dispatch({ type: 'CATEGORIES', payload: [...categories] });
    console.log(
      Cookies.get('cart_Items') ? JSON.parse(Cookies.get('cart_Items')) : []
    );
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen bg-gray-200">
        <Header />
        <div className="main flex">
          <SideBarDemo categories={categories} />
          <div className="main-section z-0   flex-1 p-6 bg-gray-200">
            <Banner />
            <Hotdeals products={products} />
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  // http://127.0.0.1:8000/api/category
  // const ress = await fetch('http://127.0.0.1:8001/api/category');
  // https://semuna-api.herokuapp.com/
  const ress = await fetch('https://semuna-api.herokuapp.com/api/category');

  const categories = await ress.json();
  const res = await fetch('https://semuna-api.herokuapp.com/api/products');
  const products = await res.json();
  // console.log(products);
  return {
    props: {
      products,
      categories,
    },
  };
}
